### ISSUE TITLE
No kernel detected

### ISSUE THREAD

**Issue by wohlbier** [ruhrie/TraceAtlas#59] opened 2020-06-16 19:39 UTC
Could you try to detect the kernel in this example?
https://github.com/wohlbier/irex

I'm not getting anything and I wonder if my installation of TraceAtlas might be broken.

Thanks.

**Comment by ruhrie** [comment] 2020-06-16 19:46
When I compiled your example I detected one kernel. It does seem to be something on your side.

The only thing I had to change was the path to `AtlasPasses.so`. I left everything else intact.

Can you share the command you used to invoke cartographer? I ran `cartographer -i raw.trc -k kernel.json -b main.0.0.preopt.bc`

**Comment by ruhrie** [comment] 2020-06-16 19:48
Another thought, did you make a release build? Sometimes clang will optimize kernels away if the optimizer runs. I won't guarantee that's the issue, but I wouldn't count it out.

**Comment by wohlbier** [comment] 2020-06-16 19:55
I tried your `cartographer` command and got the same result. The example is a `RelWithDebInfo` build, as is `TraceAtlas`. I imagine your question was about the former? If you did not change my example then you also used a `RelWithDebInfo` build. I tried to write the example so that it couldn't compile away the loop.

**Comment by ruhrie** [comment] 2020-06-16 19:57
Sorry, didn't read your readme until later. I saw a cmakelists and executed that, which means I ran the debug version.

I am honestly always surprised by what clang will compile away. I'll take a peak at the release version though now and let you know.

**Comment by wohlbier** [comment] 2020-06-16 20:06
My guess is that my installation is broken, and that it might have something to do with `vcpkg`. CMake reports that it's fine. What happens, for example, if somehow the `nlohmann_json` package doesn't get linked up properly?

**Comment by ruhrie** [comment] 2020-06-16 20:06
Ok, so I was able to recreate your problem with the release build. When I looked at the IR I wasn't able to identify the issue immediately, but I suspect the bitcode I was looking at wasn't what actually executed. I went though the cmakelists and cahnged every line that had `-Wl,--plugin-opt=save-temps` to `-Wl,--plugin-opt=emit-llvm`. This restored a single kernel being detected so the old one was probably optimized away on the backend.

**Comment by ruhrie** [comment] 2020-06-16 20:07
If the json package isn't found the headers would be missing. Its a header only library.

If you want me to commit my changes to your repo let me know.

**Comment by ruhrie** [comment] 2020-06-16 20:09
My exact commands follow:

```
cmake .. -DCMAKE_BUILD_TYPE=Release
ninja
./main-trace
/mnt/nobackup-09/Dash/Sources/bin/cartographer -i raw.trc -k kernel.json -b main
```

**Comment by wohlbier** [comment] 2020-06-16 20:18
Still no joy. Can you try again with the `save-temps` restored and see if it works when you point `cartographer` to the correct bitcode?

**Comment by ruhrie** [comment] 2020-06-16 20:42
So I just reverted and I am still detecting that single kernel. I did a git reset so everything matches your repo. I even ran your bash script to generate it. (I did have to rerun cmake to set the path to AtlasPasses though). Sorry that I was confused on this earlier.

I did notice that there is no check to make sure that the trace file is found. It will find 0 kernels if your path to the trace is incorrect. 

I also notice that you are inputting the `opt.bc`. You should be feeding cartographer `main`. Probably not the problem, but it's worth a shot.

Finally, do you detect any kernels from the earlier pipeline stages?

**Comment by ruhrie** [comment] 2020-06-16 20:48
Another question, have you run our unit tests? They should all have kernels too.

**Comment by wohlbier** [comment] 2020-06-16 20:54
`make test` shows all passed. Do I have to go in and run `cartographer` explicitly?

**Comment by ruhrie** [comment] 2020-06-16 20:55
No, cartographer did run if the tests passed. Check `build/Tests/TEST_HERE/kernel.json` to see if any kernels were detected.

**Comment by wohlbier** [comment] 2020-06-16 20:57
Doesn't look like it's finding kernels.
```
build$ find Tests -name kernel.json | xargs cat
{"BlockCounts":{},"TypeFour":{},"TypeOne":{},"TypeThree":{},"TypeThreeFive":{},"TypeTwo":{},"TypeTwoFive":{},"ValidBlocks":[]}{"BlockCounts":{},"TypeFour":{},"TypeOne":{},"TypeThree":{},"TypeThreeFive":{},"TypeTwo":{},"TypeTwoFive":{},"ValidBlocks":[]}{"BlockCounts":{},"TypeFour":{},"TypeOne":{},"TypeThree":{},"TypeThreeFive":{},"TypeTwo":{},"TypeTwoFive":{},"ValidBlocks":[]}{"BlockCounts":{},"TypeFour":{},"TypeOne":{},"TypeThree":{},"TypeThreeFive":{},"TypeTwo":{},"TypeTwoFive":{},"ValidBlocks":[]}```

**Comment by ruhrie** [comment] 2020-06-16 21:02
I agree. Either your trace or cartographer are flawed. I'm just not sure which or the best way to diagnose it going forwards.

Realistically, either I need to add debug lines to cartographer to help diagnose or to examine your trace myself. Let me know about your preference. My trace from your program is only 200 bytes so it should be easy to share.

**Comment by wohlbier** [comment] 2020-06-16 21:09
This trace is from bubbleSort.
[trc.zip](https://github.com/ruhrie/TraceAtlas/files/4789105/trc.zip)

**Comment by ruhrie** [comment] 2020-06-16 21:16
I still get kernels from that (they don't match my answers, but that makes enough sense), so it is likely that your cartographer is glitching out. I will start a branch to help diagnose this issue.

Would you rather I let you know when I have a method of generating a large log to diagnose everything, or is a more piecemeal approach your preference?

**Comment by wohlbier** [comment] 2020-06-16 21:22
Well, I don't understand the code to know what would be better. I think I'll follow your lead. If you could give me some pointers on what to look for I could do that in parallel. Like does `cartographer` depend on any particular libraries that might be hosed?

**Comment by ruhrie** [comment] 2020-06-16 21:25
The primary library that is likely at fault would be zlib honestly. The other libraries used in this context are either certified to work (llvm would segfault if anything was even remotely wrong) or are used primarily for formatting/giving me more information (spdlog/nlohmann).

I will beef up the logging and comment again with directions when it is ready. Shouldn't take long.

**Comment by wohlbier** [comment] 2020-06-16 21:26
Ok, I am using a `zlib` from spack, and not the one from `vpckg`

**Comment by ruhrie** [comment] 2020-06-16 21:44
So first, thanks for your patience. I haven't seen an issue like this before.

Second, I suspect the spack version is fine. I usually use the ubuntu version, but the vcpkg should definitely work.

Third, I just finished beefed up the logging feature. It is in the `diagnose` branch. If you run the bubblesort unit test the log should be about 1GB in size (this was really the smallest amount of debug info I could create). This should be very illuminating though. You can try a different unit test or even your program if you prefer though.

To make sure this works well please append `-v 5` and `-l log.txt` to the cartographer arguments. `-l` specifies a log file. `-v` specifies the level of logging to do. 5 is debug, 6 is trace which will produce even more data. 5 should be adequate right now though. I will ask for the resultant `kernel.json` as well though.

If you want guidance on what to look for due to the size of the file let me know.

**Comment by wohlbier** [comment] 2020-06-16 21:59
```
(base) jgwohlbier@sdh01:~/.../build$ rm -rf *
(base) jgwohlbier@sdh01:~/.../build$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/home/jgwohlbier/DSSoC/DASH/TraceAtlas/vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- The C compiler identification is Clang 9.0.1
-- The CXX compiler identification is Clang 9.0.1
-- Check for working C compiler: /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/llvm-9.0.1-mupwetisd3upwdfojfn6ztdmxmgfy3kz/bin/clang
-- Check for working C compiler: /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/llvm-9.0.1-mupwetisd3upwdfojfn6ztdmxmgfy3kz/bin/clang - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/llvm-9.0.1-mupwetisd3upwdfojfn6ztdmxmgfy3kz/bin/clang++
-- Check for working CXX compiler: /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/llvm-9.0.1-mupwetisd3upwdfojfn6ztdmxmgfy3kz/bin/clang++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LLVM 9.0.1
-- Using LLVMConfig.cmake in: /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/llvm-9.0.1-mupwetisd3upwdfojfn6ztdmxmgfy3kz/lib/cmake/llvm
-- Found ZLIB: /home/jgwohlbier/DSSoC/DASH/TraceAtlas/vcpkg/installed/x64-linux/lib/libz.a (found version "1.2.11") 
-- Found nlohmann_json: /home/jgwohlbier/DSSoC/DASH/TraceAtlas/vcpkg/installed/x64-linux/share/nlohmann_json/nlohmann_jsonConfig.cmake (found version "3.7.3") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found clang-format in /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/llvm-9.0.1-mupwetisd3upwdfojfn6ztdmxmgfy3kz/bin/clang-format
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jgwohlbier/DSSoC/DASH/TraceAtlas/build
(base) jgwohlbier@sdh01:~/.../build$ make -j
Scanning dependencies of target deat
Scanning dependencies of target libtik
Scanning dependencies of target AtlasBackend
Scanning dependencies of target AtlasPasses
Scanning dependencies of target JR
Scanning dependencies of target bow
Scanning dependencies of target kernelHasher
Scanning dependencies of target dagExtractor
Scanning dependencies of target sizeEmitter
Scanning dependencies of target bubbleSort
Scanning dependencies of target 1DCondition
Scanning dependencies of target libDetector
Scanning dependencies of target 1DBlur
Scanning dependencies of target FunctionCall
[  1%] Building C object Tests/1DBlur/CMakeFiles/1DBlur.dir/1DBlur.c.o
[  2%] Building C object TraceInfrastructure/Backend/CMakeFiles/AtlasBackend.dir/BackendPapi.c.o
[  4%] Building C object Tests/bubbleSort/CMakeFiles/bubbleSort.dir/bubbleSort.c.o
[  7%] Building C object Tests/1DCondition/CMakeFiles/1DCondition.dir/1DCondition.c.o
[  7%] Building C object Tests/FunctionCall/CMakeFiles/FunctionCall.dir/FunctionCall.c.o
[  8%] Building C object TraceInfrastructure/Backend/CMakeFiles/AtlasBackend.dir/BackendTrace.c.o
[ 10%] Building CXX object Utilities/CMakeFiles/sizeEmitter.dir/SizeEmitter.cpp.o
[ 11%] Building CXX object Utilities/CMakeFiles/kernelHasher.dir/KernelHasher.cpp.o
[ 13%] Building CXX object Utilities/CMakeFiles/libDetector.dir/libDetector.cpp.o
[ 14%] Building CXX object Utilities/CMakeFiles/bow.dir/Bow.cpp.o
[ 16%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/Trace.cpp.o
[ 17%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/TraceMem.cpp.o
[ 19%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/TraceMemIO.cpp.o
[ 20%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/Annotate.cpp.o
[ 22%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/PapiIO.cpp.o
[ 23%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/TraceIO.cpp.o
[ 25%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/Functions.cpp.o
[ 26%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/PapiExport.cpp.o
[ 28%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/CommandArgs.cpp.o
[ 29%] Building CXX object Utilities/CMakeFiles/JR.dir/JR.cpp.o
[ 32%] Building CXX object deat/CMakeFiles/deat.dir/deat.cpp.o
[ 32%] Building CXX object TraceInfrastructure/Passes/CMakeFiles/AtlasPasses.dir/AddLibrary.cpp.o
[ 34%] Building CXX object Utilities/CMakeFiles/dagExtractor.dir/DagExtractor.cpp.o
[ 35%] Building CXX object tik/lib/CMakeFiles/libtik.dir/CartographerKernel.cpp.o
[ 37%] Building CXX object tik/lib/CMakeFiles/libtik.dir/KernelInterface.cpp.o
[ 40%] Building CXX object tik/lib/CMakeFiles/libtik.dir/KernelLabel.cpp.o
[ 40%] Building CXX object tik/lib/CMakeFiles/libtik.dir/Header.cpp.o
[ 41%] Building CXX object tik/lib/CMakeFiles/libtik.dir/libtik.cpp.o
[ 43%] Building CXX object tik/lib/CMakeFiles/libtik.dir/Kernel.cpp.o
[ 44%] Building CXX object tik/lib/CMakeFiles/libtik.dir/TikKernel.cpp.o
[ 46%] Building CXX object tik/lib/CMakeFiles/libtik.dir/Util.cpp.o
[ 47%] Linking C executable 1DBlur
[ 49%] Linking C executable 1DCondition
[ 50%] Linking C executable FunctionCall
[ 52%] Linking C executable bubbleSort
[ 52%] Built target 1DCondition
[ 52%] Built target bubbleSort
[ 52%] Built target FunctionCall
[ 52%] Built target 1DBlur
[ 53%] Linking CXX static library ../../lib/libAtlasBackend.a
[ 53%] Built target AtlasBackend
[ 55%] Linking CXX executable ../bin/sizeEmitter
[ 55%] Built target sizeEmitter
[ 56%] Linking CXX shared module ../../lib/AtlasPasses.so
[ 56%] Built target AtlasPasses
[ 58%] Generating opt.bc
[ 59%] Generating opt.bc
[ 61%] Generating opt.bc
[ 62%] Generating opt.bc
Scanning dependencies of target 1DCondition-trace
Scanning dependencies of target 1DBlur-trace
Scanning dependencies of target bubbleSort-trace
Scanning dependencies of target FunctionCall-trace
[ 64%] Linking CXX executable 1DCondition-trace
[ 67%] Linking CXX executable 1DBlur-trace
[ 67%] Linking CXX executable bubbleSort-trace
[ 68%] Linking CXX executable FunctionCall-trace
[ 68%] Built target FunctionCall-trace
[ 68%] Built target 1DBlur-trace
[ 68%] Built target 1DCondition-trace
[ 68%] Built target bubbleSort-trace
[ 70%] Linking CXX executable ../bin/libDetector
[ 71%] Linking CXX executable ../bin/bow
[ 73%] Linking CXX executable ../bin/kernelHasher
[ 73%] Built target libDetector
[ 73%] Built target bow
[ 73%] Built target kernelHasher
[ 74%] Linking CXX executable ../bin/deat
[ 74%] Built target deat
[ 76%] Linking CXX executable ../bin/JR
[ 76%] Built target JR
[ 77%] Linking CXX executable ../bin/dagExtractor
[ 77%] Built target dagExtractor
[ 79%] Linking CXX static library libtik.a
[ 79%] Built target libtik
Scanning dependencies of target tikSwap
Scanning dependencies of target tik
Scanning dependencies of target cartographer
Scanning dependencies of target KernelVerifier
[ 80%] Building CXX object tik/tikSwap/CMakeFiles/tikSwap.dir/tikSwap.cpp.o
[ 82%] Building CXX object Utilities/CMakeFiles/KernelVerifier.dir/KernelVerifier.cpp.o
[ 83%] Building CXX object tik/CMakeFiles/tik.dir/tik.cpp.o
[ 85%] Building CXX object cartographer/CMakeFiles/cartographer.dir/TypeFour.cpp.o
[ 86%] Building CXX object cartographer/CMakeFiles/cartographer.dir/TypeOne.cpp.o
[ 88%] Building CXX object cartographer/CMakeFiles/cartographer.dir/TypeThree.cpp.o
[ 89%] Building CXX object cartographer/CMakeFiles/cartographer.dir/TypeTwo.cpp.o
[ 91%] Building CXX object cartographer/CMakeFiles/cartographer.dir/cartographer.cpp.o
[ 92%] Building CXX object cartographer/CMakeFiles/cartographer.dir/dot.cpp.o
[ 94%] Building CXX object cartographer/CMakeFiles/cartographer.dir/profile.cpp.o
[ 95%] Linking CXX executable ../../bin/tikSwap
[ 95%] Built target tikSwap
[ 97%] Linking CXX executable ../bin/KernelVerifier
[ 97%] Built target KernelVerifier
[ 98%] Linking CXX executable ../bin/cartographer
[ 98%] Built target cartographer
[100%] Linking CXX executable ../bin/tik
[100%] Built target tik
(base) jgwohlbier@sdh01:~/.../build$ make test
Running tests...
Test project /home/jgwohlbier/DSSoC/DASH/TraceAtlas/build
      Start  1: 1DBlur_Trace
 1/16 Test  #1: 1DBlur_Trace .....................   Passed    0.01 sec
      Start  2: 1DBlur_cartographer
 2/16 Test  #2: 1DBlur_cartographer ..............   Passed    0.01 sec
      Start  3: 1DBlur_tik
 3/16 Test  #3: 1DBlur_tik .......................   Passed    0.01 sec
      Start  4: 1DBlur_dag
 4/16 Test  #4: 1DBlur_dag .......................   Passed    0.01 sec
      Start  5: 1DCondition_Trace
 5/16 Test  #5: 1DCondition_Trace ................   Passed    0.00 sec
      Start  6: 1DCondition_cartographer
 6/16 Test  #6: 1DCondition_cartographer .........   Passed    0.01 sec
      Start  7: 1DCondition_tik
 7/16 Test  #7: 1DCondition_tik ..................   Passed    0.01 sec
      Start  8: 1DCondition_dag
 8/16 Test  #8: 1DCondition_dag ..................   Passed    0.01 sec
      Start  9: FunctionCall_Trace
 9/16 Test  #9: FunctionCall_Trace ...............   Passed    0.01 sec
      Start 10: FunctionCall_cartographer
10/16 Test #10: FunctionCall_cartographer ........   Passed    0.01 sec
      Start 11: FunctionCall_tik
11/16 Test #11: FunctionCall_tik .................   Passed    0.01 sec
      Start 12: FunctionCall_dag
12/16 Test #12: FunctionCall_dag .................   Passed    0.00 sec
      Start 13: bubbleSort_Trace
13/16 Test #13: bubbleSort_Trace .................   Passed    0.22 sec
      Start 14: bubbleSort_cartographer
14/16 Test #14: bubbleSort_cartographer ..........   Passed    0.01 sec
      Start 15: bubbleSort_tik
15/16 Test #15: bubbleSort_tik ...................   Passed    0.01 sec
      Start 16: bubbleSort_dag
16/16 Test #16: bubbleSort_dag ...................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 16

Total Test time (real) =   0.33 sec

(base) jgwohlbier@sdh01:~/.../build$ bin/cartographer -i ./Tests/bubbleSort/raw.trc -b ./Tests/bubbleSort/bubbleSort -v 5 -l log.txt

(base) jgwohlbier@sdh01:~/.../build$ zip -r test.zip bin/cartographer kernel.json log.txt ./Tests/bubbleSort/
updating: bin/cartographer (deflated 71%)
updating: kernel.json (deflated 49%)
updating: log.txt (deflated 95%)
updating: Tests/bubbleSort/ (stored 0%)
  adding: Tests/bubbleSort/raw.trc (deflated 34%)
  adding: Tests/bubbleSort/tik.bc (deflated 39%)
  adding: Tests/bubbleSort/dag.json (deflated 7%)
  adding: Tests/bubbleSort/bubbleSort (deflated 31%)
  adding: Tests/bubbleSort/CMakeFiles/ (stored 0%)
  adding: Tests/bubbleSort/CMakeFiles/CMakeDirectoryInformation.cmake (deflated 49%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort-trace.dir/ (stored 0%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort-trace.dir/build.make (deflated 81%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort-trace.dir/cmake_clean.cmake (deflated 28%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort-trace.dir/DependInfo.cmake (deflated 36%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort-trace.dir/flags.make (deflated 16%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort-trace.dir/depend.make (deflated 16%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort-trace.dir/depend.internal (deflated 16%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort-trace.dir/link.txt (deflated 86%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort-trace.dir/progress.make (deflated 27%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/ (stored 0%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/build.make (deflated 77%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/cmake_clean.cmake (deflated 33%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/bubbleSort.c.o (deflated 34%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/DependInfo.cmake (deflated 47%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/flags.make (deflated 25%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/depend.make (deflated 46%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/depend.internal (deflated 33%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/link.txt (deflated 23%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/progress.make (deflated 27%)
  adding: Tests/bubbleSort/CMakeFiles/bubbleSort.dir/C.includecache (deflated 48%)
  adding: Tests/bubbleSort/CMakeFiles/progress.marks (stored 0%)
  adding: Tests/bubbleSort/Makefile (deflated 81%)
  adding: Tests/bubbleSort/kernel.json (deflated 49%)
  adding: Tests/bubbleSort/tik.bc.h (deflated 29%)
  adding: Tests/bubbleSort/opt.bc (deflated 28%)
  adding: Tests/bubbleSort/pig.json (deflated 49%)
  adding: Tests/bubbleSort/CTestTestfile.cmake (deflated 82%)
  adding: Tests/bubbleSort/bubbleSort-trace (deflated 65%)
  adding: Tests/bubbleSort/cmake_install.cmake (deflated 58%)
```
Produces this output.
[test.zip](https://github.com/ruhrie/TraceAtlas/files/4789291/test.zip)

**Comment by ruhrie** [comment] 2020-06-16 22:13
Thanks. According to this log cartographer isn't getting a valid file handle on the trace. It isn't even calling the zlib part of the code from what I can tell.

I have updated the branch to dump a little more information that may be relevant if you want to continue down this path. It also now contains a check to ensure the trace file opened successfully. I plan to upstream that as soon as we fix this issue of yours.

Finally, can I ask was version of libcpp you are using? We do use some cpp17 features and if the version available isn't fully compatible this could cause the issues we are seeing.

**Comment by wohlbier** [comment] 2020-06-16 22:43
The version of `libc++.so` is built along with `clang`. So if I print out from main:
```
#if defined(_LIBCPP_VERSION)
    std::cerr << _LIBCPP_VERSION << std::endl;
    return 0;
#endif
```
Then I get 9000.

These are the files for this round.
[test.zip](https://github.com/ruhrie/TraceAtlas/files/4789383/test.zip)

**Comment by ruhrie** [comment] 2020-06-16 22:56
So it appears that something inside libcpp is going wrong. Either tellg or readsome is not working correctly. I just made a patch to remove the call to tellg for an alternative implementation. If readsome is the guilty party that is harder to work around, but let's only cross that bridge if necessary.

To clarify, libcpp is distributed with gcc and almost everyone links against that. libc++ is part of llvm and is only linked against if you specify it. Irrelevant now though with the latest log you shared. We know the file is opening, just not reporting correctly.

I now know within 5 lines what the problem is so we can see the light at the end of the tunnel. Sorry you have to help with this, but I can't debug something I can't reproduce without help.

**Comment by wohlbier** [comment] 2020-06-17 00:19
I don't see `libcpp` being linked. Do you mean `libgcc`?

```
(base) jgwohlbier@sdh01:~/.../build$ ldd bin/cartographer 
	linux-vdso.so.1 (0x00007ffdbe88b000)
	libz.so.1 => /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/zlib-1.2.11-cnj5zyp4vklupht52c526puig2gvajdr/lib/libz.so.1 (0x00007f003285a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0032652000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f003244e000)
	libtinfo.so.6 => /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/ncurses-6.2-uyyctmvxxeq2q33dndmsjalnz5ghp2nk/lib/libtinfo.so.6 (0x00007f003220f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0031e71000)
	libz3.so => /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/z3-4.8.7-hr6if5gnjues5f5rtsu6hry34q4fmgwx/lib/libz3.so (0x00007f0030968000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0030749000)
	libc++.so.1 => /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/llvm-9.0.1-mupwetisd3upwdfojfn6ztdmxmgfy3kz/lib/libc++.so.1 (0x00007f0032bbb000)
	libc++abi.so.1 => /DATA/SDH/packages/spack/opt/spack/linux-ubuntu18.04-broadwell/clang-9.0.1/llvm-9.0.1-mupwetisd3upwdfojfn6ztdmxmgfy3kz/lib/libc++abi.so.1 (0x00007f0032b7f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0030531000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0030140000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0032a74000)
```

**Comment by ruhrie** [comment] 2020-06-17 00:22
I meant libcpp, but it does appear you aren't linking against it. I must be mistaken. My bad.

**Comment by wohlbier** [comment] 2020-06-17 00:32
This is the output for your latest patch.
[test.zip](https://github.com/ruhrie/TraceAtlas/files/4789721/test.zip)

**Comment by ruhrie** [comment] 2020-06-17 01:16
So I've been reading and `readsome` is apparently highly implementation specific. Your implementation appears to not precache the file so it never gets read.

I'm working on a different implementation now, but it will take some time.

**Comment by ruhrie** [comment] 2020-06-17 01:27
Figured that out faster than I expected. 

From what I can tell the read function is rather uniform in its implementation so that should hopefully fix your problem. Let me know and if it does I will migrate it to master tomorrow.

**Comment by wohlbier** [comment] 2020-06-17 01:33
That certainly did something! Results for `bubbleSort` below.

```
(base) jgwohlbier@sdh01:~/.../build$ cat kernel.json 
{"BlockCounts":{"0":1,"1":513,"10":512,"11":131840,"12":131328,"13":67771,"14":131328,"15":131328,"16":512,"17":512,"18":1,"2":512,"3":512,"4":1,"5":1,"6":1,"8":1,"9":513},"Kernels":{"0":{"Blocks":[1,2,3]},"1":{"Blocks":[9,10,11,12,13,14,15,16,17]},"2":{"Blocks":[11,12,13,14,15]}},"TypeFour":{"0":[1,2,3],"1":[9,10,11,12,13,14,15,16,17],"2":[11,12,13,14,15]},"TypeOne":{"0":[1,2,3],"1":[9,10,11,12,14,15,16],"2":[9,11,12,14,15,16,17],"3":[11,12,13,14,15],"4":[11,12,14,15]},"TypeThree":{"0":[1,2,3],"1":[9,10,11,12,13,14,15,16,17],"2":[11,12,13,14,15]},"TypeThreeFive":{"0":[1,2,3],"1":[9,10,11,12,13,14,15,16,17],"2":[11,12,13,14,15]},"TypeTwo":{"0":[1,2,3],"1":[9,10,11,12,13,14,15,16],"2":[9,10,11,12,13,14,15,16,17],"3":[11,12,13,14,15]},"TypeTwoFive":{"0":[1,2,3],"1":[9,10,11,12,13,14,15,16],"2":[9,10,11,12,13,14,15,16,17],"3":[11,12,13,14,15]},"ValidBlocks":[0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18]}(base) jgwohlbier@sdh01:~/.../build$ 
```

**Comment by ruhrie** [comment] 2020-06-17 01:36
Sweet! Looks right to me. Now I know to never trust implementation specific parts of the ABI.

I will get that into dev tomorrow morning and master by the afternoon. I'll close this as soon as it hits master.

**Comment by wohlbier** [comment] 2020-06-17 01:37
Thanks much. My original reproducer now looks like it's probably correct also.

```
(base) jgwohlbier@sdh01:~/.../build$ cat kernel.json 
{"BlockCounts":{"0":1,"1":1,"10":1,"11":1,"13":1,"14":1,"15":1,"2":1,"20":1,"24":1,"28":1,"29":1,"31":1,"4":1,"42":1,"43":1,"44":1,"45":1,"5":1024,"6":1,"7":1,"8":1,"9":1},"Kernels":{"0":{"Blocks":[5]}},"TypeFour":{"0":[5]},"TypeOne":{"0":[5]},"TypeThree":{"0":[5]},"TypeThreeFive":{"0":[5]},"TypeTwo":{"0":[5]},"TypeTwoFive":{"0":[5]},"ValidBlocks":[0,1,2,4,5,6,7,8,9,10,11,13,14,15,20,24,28,29,31,42,43,44,45]}(base) jgwohlbier@sdh01:~/.../build$ 
```

**Closed** 2020-06-17 19:49 UTC
